general:
  bind: :4000
  server_name: local-proxy.f110.dev:4000
  cert_file: ./tls.crt
  key_file: ./tls.key
  role_file: ./roles.yaml
  proxy_file: ./proxies.yaml
  certificate_authority:
    cert_file: ./ca.crt
    key_file: ./ca.key
    organization: test
    organization_unit: dev
    country: jp
  root_users:
    - fmhrit@gmail.com
identity_provider:
  provider: google
  client_id: 70353433905-pqk31pc51d76hnk225tssjh9mkaof3da.apps.googleusercontent.com
  client_secret_file: ./client_secret
  extra_scopes: ["email"]
  redirect_url: https://local-proxy.f110.dev:4000/auth/callback
datastore:
  url: etcd://embed
  data_dir: ./data
frontend_proxy:
  access_log: ./access.log
  signing_secret_key_file: ./privatekey.pem
  github_webhook_secret_file: ./github_webhook_secret
  expect_ct: true
  session:
    type: secure_cookie
    key_file: ./cookie_secret
dashboard:
  enable: true
  bind: :4100