general:
  # Listen address of the proxy. This address is a main socket.
  # A lot of traffic come here.
  # Default value is :4000
  bind: :4000
  # Start http server. HTTP server will redirect all traffic to https.
  enable_http: true
  # Listen address of HTTP server
  bind_http: :4001
  # Enable debug log. If you are not the developer, use false.
  debug: true
  # The name of server. This domain is the name your users will use.
  # server name has to include the port if your users can't access by well-known port.
  server_name: local-proxy.f110.dev:4000
  signing_private_key_file: ./privatekey.pem
  internal_token_file: ./internal_token
  cert_file: ./tls.crt
  key_file: ./tls.key
  role_file: ./roles.yaml
  proxy_file: ./proxies.yaml
  rpc_permission_file: ./rpc_permissions.yaml
  rpc_target: 127.0.0.1:4002
  certificate_authority:
    cert_file: ./ca.crt
    key_file: ./ca.key
    organization: test
    organization_unit: dev
    country: jp
  root_users:
    - fmhrit@gmail.com
rpc_server:
  bind: :4002
  metrics_bind: :4005
  enable: true
identity_provider:
  provider: google
  client_id: 70353433905-pqk31pc51d76hnk225tssjh9mkaof3da.apps.googleusercontent.com
  client_secret_file: ./client_secret
  extra_scopes: ["email"]
  redirect_url: https://local-proxy.f110.dev:4000/auth/callback
datastore:
  url: etcd://embed
  data_dir: ./data
frontend_proxy:
  access_log: ./access.log
  github_webhook_secret_file: ./github_webhook_secret
  expect_ct: true
  session:
    type: secure_cookie
    key_file: ./cookie_secret
dashboard:
  enable: true
  bind: :4100
  ca_cert_file: ./ca.crt
  template:
    loader: shotgun