general:
  role_file: ./roles.yaml
  proxy_file: ./proxies.yaml
  certificate_authority:
    cert_file: ./ca.crt
    key_file: ./ca.key
    organization: test
    organization_unit: dev
    country: jp
identity_provider:
  bind: :4001
  endpoint_url: https://local-proxy.f110.dev:4001/auth
  provider: google
  client_id: 70353433905-pqk31pc51d76hnk225tssjh9mkaof3da.apps.googleusercontent.com
  client_secret_file: ./client_secret
  extra_scopes: ["email"]
  redirect_url: https://local-proxy.f110.dev:4001/auth/callback
  cert_file: ./tls.crt
  key_file: ./tls.key
datastore:
  url: etcd://embed
  data_dir: ./data
  namespace: /lp
frontend_proxy:
  bind: :4000
  cert_file: ./tls.crt
  key_file: ./tls.key
  signing_secret_key_file: ./privatekey.pem
  session:
    type: secure_cookie
    key_file: ./cookie_secret
logger:
  level: debug
  encoding: console
dashboard:
  enable: true
  bind: :4100
  template:
    loader: shotgun
    dir: tmpl/dashboard