# permissions to do edit backends.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backend-editor-role
rules:
- apiGroups:
  - proxy.f110.dev
  resources:
  - backends
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - proxy.f110.dev
  resources:
  - backends/status
  verbs:
  - get
  - patch
  - update
