apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: basic-manager-role
rules:
- apiGroups:
    - monitoring.coreos.com
  resources:
    - servicemonitors
    - podmonitors
  verbs:
    - list
    - get
    - create
    - delete
    - update
    - patch
    - watch
- apiGroups:
    - etcd.database.coreos.com
  resources:
    - etcdclusters
  verbs:
    - list
    - get
    - create
    - delete
    - update
    - patch
    - watch
- apiGroups:
    - cert-manager.io
  resources:
    - certificates
    - clusterissuers
  verbs:
    - get
    - list
    - watch
    - create
    - delete
    - update
    - patch
- apiGroups:
    - "*"
  resources:
    - secrets
    - configmaps
    - deployments
    - services
    - poddisruptionbudgets
    - cronjobs
  verbs:
    - "*"