# permissions to do edit lagrangianproxies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lagrangianproxy-editor-role
rules:
- apiGroups:
  - proxy.f110.dev
  resources:
  - lagrangianproxies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - proxy.f110.dev
  resources:
  - lagrangianproxies/status
  verbs:
  - get
  - patch
  - update
