# permissions to do viewer lagrangianproxies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lagrangianproxy-viewer-role
rules:
- apiGroups:
  - proxy.f110.dev
  resources:
  - lagrangianproxies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - proxy.f110.dev
  resources:
  - lagrangianproxies/status
  verbs:
  - get
