# permissions to do viewer proxies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: proxy-viewer-role
rules:
- apiGroups:
  - proxy.f110.dev
  resources:
  - proxies
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - proxy.f110.dev
  resources:
  - proxies/status
  verbs:
  - get
