# permissions to do edit roles.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: role-editor-role
rules:
- apiGroups:
  - proxy.f110.dev
  resources:
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - proxy.f110.dev
  resources:
  - roles/status
  verbs:
  - get
  - patch
  - update
