
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - proxy.f110.dev
  resources:
  - backends
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - proxy.f110.dev
  resources:
  - backends/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - proxy.f110.dev
  resources:
  - lagrangianproxies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - proxy.f110.dev
  resources:
  - lagrangianproxies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - proxy.f110.dev
  resources:
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - proxy.f110.dev
  resources:
  - roles/status
  verbs:
  - get
  - patch
  - update
