
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: lag-proxy
rules:
- apiGroups:
  - proxy.f110.dev
  resources:
  - backends
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - proxy.f110.dev
  resources:
  - backends/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - proxy.f110.dev
  resources:
  - proxies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - proxy.f110.dev
  resources:
  - proxies/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - proxy.f110.dev
  resources:
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - proxy.f110.dev
  resources:
  - roles/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - proxy.f110.dev
  resources:
  - rpcpermissions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - proxy.f110.dev
  resources:
  - rpcpermissions/status
  verbs:
  - get
  - patch
  - update
