# permissions to do edit rpcpermissions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rpcpermission-editor-role
rules:
- apiGroups:
  - proxy.f110.dev
  resources:
  - rpcpermissions
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - proxy.f110.dev
  resources:
  - rpcpermissions/status
  verbs:
  - get
  - patch
  - update
