# permissions to do viewer rpcpermissions.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rpcpermission-viewer-role
rules:
- apiGroups:
  - proxy.f110.dev
  resources:
  - rpcpermissions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - proxy.f110.dev
  resources:
  - rpcpermissions/status
  verbs:
  - get
