apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: lag-proxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  labels:
    control-plane: controller-manager
spec:
  selector:
    matchLabels:
      control-plane: controller-manager
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      serviceAccountName: lag-proxy
      containers:
        - name: operator
          image: quay.io/f110/lagrangian-proxy-operator:v0.1.4
          args: []
          resources:
            limits:
              cpu: 100m
              memory: 30Mi
            requests:
              cpu: 100m
              memory: 20Mi
      terminationGracePeriodSeconds: 10
