apiVersion: apps/v1
kind: Deployment
metadata:
  name: lag-proxy-operator
  labels:
    control-plane: lag-proxy-operator
spec:
  selector:
    matchLabels:
      control-plane: lag-proxy-operator
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: lag-proxy-operator
    spec:
      serviceAccountName: lag-proxy
      containers:
        - name: operator
          image: quay.io/f110/lagrangian-proxy-operator:v0.5.0
          imagePullPolicy: Always
          args:
            - -lease-lock-name=operator
            - -lease-lock-namespace=$(MY_NAMESPACE)
            - -cluster-domain=cluster.local
            - -v=4
          env:
            - name: MY_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          resources:
            limits:
              cpu: 100m
              memory: 30Mi
            requests:
              cpu: 100m
              memory: 20Mi
      terminationGracePeriodSeconds: 10
