apiVersion: proxy.f110.dev/v1
kind: Proxy
metadata:
  name: proxy-sample
spec:
  replicas: 3
  domain: local-proxy.f110.dev
  port: 443
  organization: test
  administratorUnit: super
  backendSelector:
    instance: proxy-sample
  roleSelector:
    instance: proxy-sample
  issuerRef:
    name: ca-issuer
    kind: Issuer
  identityProvider:
    provider: google
    clientId: 70353433905-pqk31pc51d76hnk225tssjh9mkaof3da.apps.googleusercontent.com
    clientSecretRef:
      name: client-secret
      key: client_secret
    redirectUrl: https://local-proxy.f110.dev:4000/auth/callback
  rootUsers:
    - fmhrit@gmail.com
  session:
    type: secure_cookie
    keySecretRef:
      name: cookie-secret
  monitor:
    prometheusMonitoring: true
    labels:
      k8s-app: etcd
  defragment:
    schedule: "18 13 * * *"