apiVersion: proxy.f110.dev/v1
kind: Backend
metadata:
  name: backend-sample
  labels:
    instance: lagrangianproxy-sample
spec:
  upstream: http://localhost:4502
  permissions:
    - name: all
      locations:
        - get: /
